version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MPuzo1920
      POSTGRES_DB: welbex
    volumes:
      - dbdata:/var/lib/postgresql/data

  welbex:
    image: stgolovin/welbex
    ports:
      - "8000:8000"
    depends_on:
      - welbex_migrations

  welbex_migrations:
    image: stgolovin/welbex
    depends_on:
      - db
    command:  sh -c "python3 manage.py migrate && python3 manage.py loaddata json_file.json && python3 manage.py loaddata cargo.json && python3 manage.py loaddata vehicles.json"
    

volumes:
  dbdata:
