# Generated by Django 4.2.1 on 2023-05-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0002_cargo_location_vehicle_delete_topic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='zip',
            field=models.CharField(),
        ),
    ]
